version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: ~/circleci_test
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: circleci_test-{{ .Branch }}-{{ checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
          key: circleci_test-{{ .Branch }}-{{ checksum "package-lock.json"}}
          paths:
            - "nodes_modules"
      - run: npm run test -- --no-watch --no-progress
workflows:
    build-and-test:
      jobs:
        - build-and-test
